export const personal = {
  name: 'PM Gowtham',
  role: 'Web Developer & Machine Learning Enthusiast',
  tagline: 'Building scalable, intelligent applications at the intersection of elegant code and mathematical intuition.',
  bio: "I'm a second-year Integrated M.Tech student passionate about crafting web experiences and intelligent systems. I approach both web development and machine learning from first principles — understanding the mathematics and building from scratch before reaching for libraries.",
  bio2: "From interactive frontends to neural network implementations, I believe in understanding the 'why' behind every tool I use.",
  email: 'gowtham.developer07@example.com',
  github: 'https://github.com/Gowtham24MIS',
  linkedin: 'https://www.linkedin.com/in/p-m-gowtham-022756355/',
  twitter: 'https://twitter.com',
  resume: '/resume1.pdf',
  // Replace with your actual image path: src/assets/profile.jpg
}

export const skills = [
  {
    category: 'Frontend',
    icon: '⬡',
    color: 'acid',
    items: [
      { name: 'HTML5', level: 95 },
      { name: 'TailwindCSS', level: 90 },
      { name: 'JavaScript', level: 88 },
      { name: 'React.js', level: 85 },
    ],
  },
  {
    category: 'Backend & ML',
    icon: '◈',
    color: 'glow',
    items: [
      { name: 'Python', level: 90 },
      { name: 'Flask', level: 80 },
      { name: 'Machine Learning', level: 75 },
      { name: 'NumPy / Pandas', level: 82 },
    ],
  },
  {
    category: 'Tools & Concepts',
    icon: '◎',
    color: 'plasma',
    items: [
      { name: 'Git & GitHub', level: 85 },
      { name: 'REST APIs', level: 80 },
      { name: 'Linear Algebra', level: 78 },
      { name: 'Data Structures', level: 82 },
    ],
  },
]

export const techBadges = [
  { name: 'HTML5', icon: '🌐' },
  { name: 'TailwindCSS', icon: '🎨' },
  { name: 'JavaScript', icon: '⚡' },
  { name: 'React.js', icon: '⚛️' },
  { name: 'Python', icon: '🐍' },
  { name: 'Flask', icon: '🔥' },
  { name: 'Machine Learning', icon: '🧠' },
  { name: 'NumPy', icon: '📊' },
  { name: 'Git', icon: '🔀' },
  { name: 'REST APIs', icon: '🔗' },
]

export const projects = [
  {
    id: 1,
    title: 'Indominous Labs',
    description: 'A modern and responsive Indominous labs website built using React and TailwindCSS. It includes sections like Home, Services, Membership, and Contact with a clean UI and smooth user experience. Designed for performance, responsiveness, and real-world usability.',
    tags: ['React', 'TailwindCSS'],
    color: 'acid',
    accentColor: '#a8ff3e',
    image: '/projects/indominous.png',
    demo: 'https://reforming-indominous-ui.vercel.app/',
    github: 'https://github.com/Gowtham24MIS/reforming-indominous-ui',
    featured: false,
    stats: [{ label: 'Year', value: '2026' }, { label: 'Stack', value: 'React' }],
  },
  {
    id: 2,
    title: 'Aarthi sweets and bakery',
    description: 'A modern and responsive Sweets shop website built using React and TailwindCSS. It includes sections like Home, Services, Membership, and Contact with a clean UI and smooth user experience. Designed for performance, responsiveness, and real-world usability.',
    tags: ['React', 'TailwindCSS'],
    color: 'acid',
    accentColor: '#a8ff3e',
    image: '/projects/aarthi.png',
    demo: 'https://ambattur-aarthi.vercel.app/',
    github: 'https://github.com/Gowtham24MIS/aarthi',
    featured: false,
    stats: [{ label: 'Year', value: '2026' }, { label: 'Stack', value: 'React' }],
  },
  {
    id: 3,
    title: 'Gym Fitness Center',
    description: 'A modern and responsive Gym Fitness Center website built using React and TailwindCSS. It includes sections like Home, Services, Membership, and Contact with a clean UI and smooth user experience. Designed for performance, responsiveness, and real-world usability.',
    tags: ['React', 'TailwindCSS'],
    color: 'acid',
    accentColor: '#a8ff3e',
    image: '/projects/gym.png',
    demo: 'https://gym-fitness-indol.vercel.app/',
    github: 'https://github.com/Gowtham24MIS/gym-fitness',
    featured: false,
    stats: [{ label: 'Year', value: '2026' }, { label: 'Stack', value: 'React' }],
  },
  {
    id: 4,
    title: 'Cafe Website',
    description: 'A modern and responsive Cafe website built using React and TailwindCSS. It includes sections like Home, Services, Membership, and Contact with a clean UI and smooth user experience. Designed for performance, responsiveness, and real-world usability.',
    tags: ['React', 'TailwindCSS'],
    color: 'acid',
    accentColor: '#a8ff3e',
    image: '/projects/cafe.png',
    demo: 'https://cafe-kohl-seven.vercel.app/',
    github: 'https://github.com/Gowtham24MIS/cafe',
    featured: false,
    stats: [{ label: 'Year', value: '2026' }, { label: 'Stack', value: 'React' }],
  },
  {
    id: 5,
    title: 'Beauty Salon Website',
    description: 'A modern and responsive Beauty Salon website built using React and TailwindCSS. It includes sections like Home, Services, Membership, and Contact with a clean UI and smooth user experience. Designed for performance, responsiveness, and real-world usability.',
    tags: ['React', 'TailwindCSS'],
    color: 'acid',
    accentColor: '#a8ff3e',
    image: '/projects/beauty-saloon.png',
    demo: 'https://beauty-saloon-iota.vercel.app/',
    github: 'https://github.com/Gowtham24MIS/Beauty-saloon',
    featured: false,
    stats: [{ label: 'Year', value: '2026' }, { label: 'Stack', value: 'React' }],
  },
  {
    id: 6,
    title: 'Bakery shop Website',
    description: 'A modern and responsive Bakery shop website built using React and TailwindCSS. It includes sections like Home, Services, Membership, and Contact with a clean UI and smooth user experience. Designed for performance, responsiveness, and real-world usability.',
    tags: ['React', 'TailwindCSS'],
    color: 'acid',
    accentColor: '#a8ff3e',
    image: '/projects/bakery.png',
    demo: 'https://sample-bakery-ten.vercel.app/',
    github: 'https://github.com/Gowtham24MIS/sample-bakery',
    featured: false,
    stats: [{ label: 'Year', value: '2026' }, { label: 'Stack', value: 'React' }],
  },
  {
    id: 7,
    title: 'Restaurant Website',
    description: 'A modern and responsive Restaurant website built using React and TailwindCSS. It includes sections like Home, Services, Membership, and Contact with a clean UI and smooth user experience. Designed for performance, responsiveness, and real-world usability.',
    tags: ['React', 'TailwindCSS'],
    color: 'acid',
    accentColor: '#a8ff3e',
    image: '/projects/hotel.png',
    demo: 'https://restaurant-lime-sigma-58.vercel.app/',
    github: 'https://github.com/Gowtham24MIS/Restaurant',
    featured: false,
    stats: [{ label: 'Year', value: '2026' }, { label: 'Stack', value: 'React' }],
  },
  {
    id: 8,
    title: 'Telecom Customer Churn Prediction',
    description: 'A modern and responsive Telecom Customer Churn Prediction project built using Machine Learning. It is being made using the Supervised Learning approach, Includes many metrics and fixes which makes the model effective for the real world. Designed for performance, responsiveness, and real-world usability.',
    tags: ['Machine Learning', 'Python', 'Data Science'],
    color: 'acid',
    accentColor: '#a8ff3e',
    image: '/projects/churn-predictor.png',
    demo: 'https://telecom-customer-churn-predictor.streamlit.app/',
    github: 'https://github.com/Gowtham24MIS/customer-churn-prediction',
    featured: false,
    stats: [{ label: 'Year', value: '2026' }, { label: 'Stack', value: 'React' }],
  },

]

export const timeline = [
  {
    year: '2023',
    title: 'The Beginning',
    description: 'Started my Integrated M.Tech journey. Built my first HTML/CSS pages and fell in love with turning designs into reality.',
    tags: ['HTML', 'CSS', 'JavaScript'],
    icon: '🌱',
    side: 'left',
  },
  {
    year: '2023',
    title: 'React & Modern Web',
    description: 'Dove deep into component-based architecture with React. Discovered TailwindCSS and never looked back. Built full responsive web apps.',
    tags: ['React', 'TailwindCSS', 'Vite'],
    icon: '⚛️',
    side: 'right',
  },
  {
    year: '2024',
    title: 'Python & Backend',
    description: 'Expanded into server-side development with Python and Flask. Learned to build REST APIs and connect frontends to intelligent backends.',
    tags: ['Python', 'Flask', 'REST APIs'],
    icon: '🔧',
    side: 'left',
  },
  {
    year: '2024',
    title: 'Machine Learning',
    description: 'Started learning ML from mathematical fundamentals — linear algebra, calculus, statistics. Built neural networks and classifiers from scratch without frameworks.',
    tags: ['NumPy', 'Linear Algebra', 'ML Math'],
    icon: '🧠',
    side: 'right',
  },
  {
    year: '2025',
    title: 'Full-Stack AI Apps',
    description: 'Combining web development expertise with ML knowledge to build intelligent, production-ready applications that solve real problems.',
    tags: ['Full-Stack', 'AI Integration', 'Production'],
    icon: '🚀',
    side: 'left',
  },
]
